#!/usr/bin/env bash
# Commands to install nginx
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'NGINX HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
